-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 17:48:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_judge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_judge` DEFAULT CHARACTER SET utf8mb4 ;
USE `online_judge` ;

-- -----------------------------------------------------
-- Table `online_judge`.`problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`problems` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` JSON NULL,
  `accept` MEDIUMINT NULL,
  `fail` MEDIUMINT NULL,
  `is_robot_problem` TINYINT(1) NULL,
  `judgeer_info` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `authority` VARCHAR(20) NOT NULL,
  `user_info` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`contest` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `start_time` DATETIME NULL,
  `duration` TIME NULL,
  `contest_info` JSON NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`language` (
  `language` VARCHAR(45) NOT NULL,
  `run_cmd` TEXT NULL,
  PRIMARY KEY (`language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`submit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`submit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `submit_state` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `run_time` TIME NULL,
  `submit_time` DATETIME NULL,
  `language` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `problems_id` INT UNSIGNED NOT NULL,
  `contest_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_submit_language1_idx` (`language` ASC) VISIBLE,
  INDEX `fk_submit_problems1_idx` (`problems_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_submit_contest1_idx` (`contest_id` ASC) VISIBLE,
  CONSTRAINT `fk_submit_language1`
    FOREIGN KEY (`language`)
    REFERENCES `online_judge`.`language` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submit_problems1`
    FOREIGN KEY (`problems_id`)
    REFERENCES `online_judge`.`problems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submit_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_judge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submit_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `online_judge`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`contest_has_problems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`contest_has_problems` (
  `contest_id` INT NOT NULL,
  `problems_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`contest_id`, `problems_id`),
  INDEX `fk_contest_has_problems_problems1_idx` (`problems_id` ASC) VISIBLE,
  INDEX `fk_contest_has_problems_contest1_idx` (`contest_id` ASC) VISIBLE,
  CONSTRAINT `fk_contest_has_problems_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `online_judge`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contest_has_problems_problems1`
    FOREIGN KEY (`problems_id`)
    REFERENCES `online_judge`.`problems` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_judge`.`user_join_contest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_judge`.`user_join_contest` (
  `user_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `contest_id`),
  INDEX `fk_user_has_contest_contest1_idx` (`contest_id` ASC) VISIBLE,
  INDEX `fk_user_has_contest_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_contest_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_judge`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_contest_contest1`
    FOREIGN KEY (`contest_id`)
    REFERENCES `online_judge`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'online_judge_admin' IDENTIFIED BY 'qweasd';

GRANT ALL ON `online_judge`.* TO 'online_judge_admin';
CREATE USER 'online_judge_user' IDENTIFIED BY 'qweasd';

GRANT SELECT ON TABLE `online_judge`.* TO 'online_judge_user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `online_judge`.* TO 'online_judge_user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
